### ISSUE TITLE
Gta 5 Offline map update

### ISSUE THREAD

**Issue by ajayrakhyani** [PLTytus/GTAWeb#15]
**Describe your idea:**
...

**Examples (if you was inspired by some other website or project):**
...

**Additional context (if you have somthing more to add, eg. how it will help or improve the webiste):**
...

Hey brother
I am really a big fan of you. The hardwork you do on creating and continuously updating the website
I just wanted to tell you
You are continuously updating the gta online map
But not gta 5 offline one
Like recently you added shopping list which i think will be same as offline as well just some minor changes needs to be made

Also you can update the offline map other collectibles
Like body armor
Health pickups
Weapons and other
I really would like you to update it as other websites are not much interactive like your's
Theu dont update images .
If you need any help with this do let me know and i am happy to help :)

**Comment by PLTytus** [comment]
Shopping category added: https://gtaweb.eu/gtao-map/ls2/z1dz40

Weapons, health, body armors I will try to find and on both Online and SP map, there is also another suggestions for those: https://github.com/PLTytus/GTAWeb/issues/13

If there is any other content, you believe should be added to the SP please let me know in this issue. I will keep this open because not all content mentioned by you was added.

**Comment by PLTytus** [comment]
Weapons, health and body armor added: https://github.com/PLTytus/GTAWeb/issues/13#issuecomment-1701719631

Now, all mentioned content by you is added, so I am closing ticket but I have something on TODO list for singleplayer, I will add everything I have in mind when I will find some time :)
