### ISSUE TITLE
Wrong in-game time (day of week)

### ISSUE THREAD

**Issue by xgalto** [PLTytus/GTAWeb#30]
It seems like the map has the wrong time now (maybe since daylight savings). The map lists the in-game time as Thursday 20:23 right now, but it should be Friday 20:23.

It also seem to affect features like Exotic exports and Street Dealers where the map no longer matches what I see in-game.

**Comment by PLTytus** [comment]
> maybe since daylight savings
Timestamp (which is amount of seconds starting January 1st, 1970) is not affected by DST.
> It also seem to affect features like Exotic exports and Street Dealers where the map no longer matches what I see in-game.
Daily content is changing on 6 and 7 am utc. If what you see in-game is not accurate with map, you should reload the map and best also change in-game session. In-game feature is not connected to locations of daily content.

I am aware of this issue since introducing the in-game time feature. The day of week weirdly shifts sometimes, I am trying to figure out the pattern. All other data (hour, minutes, wheater) are accurate (and the ones I spoke above). There might be some diffrence in couple of minutes due to the feature bases on time setted on your device, and in-game time bases on time setted for the game server.

**Comment by PLTytus** [comment]
I've made a correction. Currently it is ok but it will probably break in a few of days.

Sharing current code for this, maybe someone will figure it out:
```let weekday = (Math.floor(timestamp / INGAME_DAY_LENGTH) + 3 /* TODO: correction probably shifts between 3 and 4 */) % 7; // 0 is sunday```

**Comment by PLTytus** [comment]
I am testing new solution, it is long term test, I will let you know if results will be positive.

**Comment by PLTytus** [comment]
https://twitter.com/PLTytus/status/1745732127763677445
