### ISSUE TITLE
Muscle vehicles

### ISSUE THREAD

**Issue by Carlover2471** [PLTytus/GTAWeb#41]
**Basic info (please complete all of the following, even if you believe it is not important):**
- Priority: [in your opinion: Very High / High / Normal / Low / Does not bother / I don't know]
- Subpage name: [e.g. map, toolkit]
- Supbage URL: [e.g. https://gtaweb.eu/gtao-map/ls/2]
- Setted language: [e.g. English, Polish]
- Device type: [e.g. mobile, desktop]
- Device: [e.g. iPhone 6, PC, MacBook]
- OS and its version: [e.g. iOS 16.5, Windows 10 Home, Windows 11, ...]
- Browser and its version [e.g. chrome 114.0.5735.110]

**Describe the issue (a clear and detailed description of the issue):**
... the vamos and the Yosemite can’t use their natural wheelie glitch anymore

**To Reproduce  (detailed steps to reproduce the behavior):**
1. ...call car out
2. ...get in car 
3. ...hold down rb or ebrake and rev the engine 
4. Let go of rb or ebrake and the vamos will just fall on its face and the Yosemite will just prop up and do a standing burnout instead of launching forward

**Expected behavior  (how it should work):**
...

**Screenshots or video (if you can provied them,  a screenshot of the developer's console from when the problem occurred might be useful):**
...

**Additional context (if you have somthing more to add):**
...

**Comment by PLTytus** [comment]
I cannot fix something in the game, because I am not working on the game, or for Rockstar, or with Rockstar, nor I have contact with them.
This is repository for issues and suggestions for [GTAWeb.eu](https://GTAWeb.eu) website (which is fan made product), not for GTAV, GTA Online, or any GTA game.
Please, contact [Rockstar Support](https://support.rockstargames.com/).
