### ISSUE TITLE
Integrate data from game (Story Mode and Online)

### ISSUE THREAD

**Issue by DarthVader37** [PLTytus/GTAWeb#6]
**Describe your idea:**
I want a feature that allows us to sign into the account we play GTA on (Xbox, PlayStation, PC) so everything we have found so far (LD Organic Products, Action Figures, Playing Cards, Spaceship Parts, Letter Scraps, etc.) will automatically be marked as "done", allowing us to find the remaining items quicker and easier after we have signed in. 

**Examples (if you was inspired by some other website or project):**
Let's say someone has found and destroyed 45/50 of the signal jammers and they just need to find the other 5, once they sign in, the 45 they've already found will be checked off, allowing them to find the remaining 5, saving the person time from painstakingly going through the entire list, looking for everything they've completed just to find the ones that haven't been found yet. 

**Additional context (if you have something more to add, eg. how it will help or improve the website):**
...

**Comment by PLTytus** [comment]
That would be great, unfortunatelly such integration with Social Club is not possible.

If it were possible (by some hidden endpoint because there is no official API or something like that), it would be really difficult to implement in the first place, and keeping it up to date with continuously changing Social Club would be a nightmare. They could also block necessary endpoints - there is a big entier website will break in this situation.

Login feature to store users data across devices is possible - it would probably require enormous amount of changes - but this is another subject for consideration.
